# Generated by Django 3.1.2 on 2020-10-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20201026_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessiblelocal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='classification',
            field=models.CharField(max_length=50),
        ),
    ]
